image:
  repository: mocontainers2022.azurecr.io/redis
  tag: v1

ContainerName: azure-vote-back

ContainerPort: 6379

service:
  type: ClusterIP
  port: 6379

#env:
#- name: ALLOW_EMPTY_PASSWORD
#  value: "yes"

env:
  ALLOW_EMPTY_PASSWORD: "yes"
