image:
  repository: mocontainers2022.azurecr.io/azure-vote-front
  tag: v1

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: azure-front.local
      paths:
        - path: /
          pathType: Prefix
